# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whatsapp-app
  template:
    metadata:
      labels:
        app: whatsapp-app
    spec:
      containers:
        - name: whatsapp-app
          image: your_dockerhub_username/whatsapp-microservice:latest
          ports:
            - containerPort: 3000
