apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  db_host: bXlzcWw=           # 'mysql' em Base64
  db_user: cm9vdA==           # 'root' em Base64
  db_password: cGFzc3dvcmQ=   # 'password' em Base64
  db_name: d2hhdHNhcHBfZGI=   # 'whatsapp_db' em Base64

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmq_url: YW1xcDovL3JhYmJpdG1xQHJhYmJpdG1x # 'amqp://rabbitmq' em Base64
