apiVersion: v1
kind: Service
metadata:
  name: whatsapp-service
spec:
  selector:
    app: whatsapp-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # Você pode usar LoadBalancer se estiver em um ambiente de produção
